name: Setup OpenFOAM
description: Set up a specific version of OpenFOAM
inputs:
  openfoam-version:
    description: Version of OpenFOAM to set up
  cache:
    description: Whether to cache the OpenFOAM installation for future runs
    default: true
branding:
  icon: grid
  color: blue
runs:
  using: "composite"
  steps:
    - name: Prepare for install
      id: prep
      run: |
        if [ $(uname) == "Darwin" ]; then
          echo "openfoam-bashrc=/Applications/OpenFOAM-v${{ inputs.openfoam-version }}.app/Contents/Resources/etc/bashrc" >> "$GITHUB_OUTPUT"
          echo "openfoam-shell=/Applications/OpenFOAM-v${{ inputs.openfoam-version }}.app/Contents/Resources/etc/openfoam" >> "$GITHUB_OUTPUT"
        elif [ ${{ inputs.openfoam-version }} -lt 1000 ]; then
          export DEBIAN_FRONTEND=noninteractive
          if [ $(id -u) -eq 0 ]; then
            apt-get install -y wget software-properties-common || apt update && apt-get install -y wget software-properties-common
            sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
            add-apt-repository http://dl.openfoam.org/ubuntu
            apt update
          else
            sudo apt-get install -y wget software-properties-common || sudo apt update && sudo apt-get install -y wget software-properties-common
            sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
            sudo add-apt-repository http://dl.openfoam.org/ubuntu
            sudo apt update
          fi
          echo "apt-package=openfoam${{ inputs.openfoam-version }}" >> $GITHUB_OUTPUT
          echo "openfoam-bashrc=/opt/openfoam${{ inputs.openfoam-version }}/etc/bashrc" >> "$GITHUB_OUTPUT"
        else
          export DEBIAN_FRONTEND=noninteractive
          if [ $(id -u) -eq 0 ]; then
            sudo apt-get install -y curl || apt update && apt-get install -y curl
            curl -s https://dl.openfoam.com/add-debian-repo.sh | bash
          else
            sudo apt-get install -y curl || sudo apt update && sudo apt-get install -y curl
            curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
          fi
          echo "apt-package=openfoam${{ inputs.openfoam-version }}-default" >> "$GITHUB_OUTPUT"
          echo "openfoam-bashrc=/usr/lib/openfoam/openfoam${{ inputs.openfoam-version }}/etc/bashrc" >> "$GITHUB_OUTPUT"
          echo "openfoam-shell=/usr/lib/openfoam/openfoam${{ inputs.openfoam-version }}/etc/openfoam" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: Install OpenFOAM on Linux (with caching)
      if: steps.prep.outputs.apt-package && inputs.cache && !job.container
      uses: eth-pkg/apt-deb-cache@v0.2.5
      with:
        packages: ${{ steps.prep.outputs.apt-package }}
    - name: Install OpenFOAM on Linux (without caching)
      if: steps.prep.outputs.apt-package && (!inputs.cache || job.container)
      run: |
        export DEBIAN_FRONTEND=noninteractive
        if [ $(id -u) -eq 0 ]; then
          apt-get install -y ${{ steps.prep.outputs.apt-package }}
        else
          sudo apt-get install -y ${{ steps.prep.outputs.apt-package }}
        fi
      shell: bash
    - name: Get OS version
      if: runner.os == 'macOS' && inputs.cache
      id: os-version
      uses: sersoft-gmbh/os-version-action@v3
    - name: Cache OpenFOAM on macOS
      if: runner.os == 'macOS' && inputs.cache
      id: cache-macos
      uses: actions/cache@v4
      with:
        key: setup-openfoam-${{ inputs.openfoam-version }}-${{ runner.os }}-${{ steps.os-version.outputs.version }}-${{ runner.arch }}
        path: /Applications/OpenFOAM-v${{ inputs.openfoam-version }}.app
    - name: Install OpenFOAM on macOS
      if: runner.os == 'macOS' && steps.cache-macos.outputs.cache-hit != 'true'
      run: |
        brew install --no-quarantine gerlero/openfoam/openfoam@${{ inputs.openfoam-version }}
      shell: bash
    - name: Activate OpenFOAM for future steps
      run: |
        OLD_PATH="$PATH"
        source "${{ steps.prep.outputs.openfoam-bashrc }}" || true

        for var in "${!WM_@}"; do
          echo "$var=${!var}" >> "$GITHUB_ENV"
        done

        for var in "${!FOAM_@}"; do
          echo "$var=${!var}" >> "$GITHUB_ENV"
        done

        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

        echo "${PATH/%:$OLD_PATH}" >> "$GITHUB_PATH"
      shell: bash
    - name: Add shell session commands to PATH
      if: steps.prep.outputs.openfoam-shell
      run: |
        mkdir -p ~/.setup-openfoam/bin
        ln -s "${{ steps.prep.outputs.openfoam-shell }}" ~/.setup-openfoam/bin/openfoam${{ inputs.openfoam-version }}
        ln -s "${{ steps.prep.outputs.openfoam-shell }}" ~/.setup-openfoam/bin/openfoam
        echo ~/.setup-openfoam/bin >> "$GITHUB_PATH"
      shell: bash
